#!/usr/bin/env python3
import sys

# 引数（余計な指定）があったら、ステータス1（異常）で終了する
if len(sys.argv) > 1:
    sys.exit(1)

def main():
    # 変換テーブル
    kyuji_map = str.maketrans({
        '國': '国', '立': '立', '大': '大', '學': '学',
        '會': '会', '社': '社', '圓': '円', '廣': '広',
        '來': '来', '氣': '気', '體': '体', '實': '実'
    })
    
    # 変換処理
    for line in sys.stdin:
        sys.stdout.write(line.translate(kyuji_map))

if __name__ == '__main__':
    main()
